version: "3.5"

networks:
  cosmos-monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml.edited:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - cosmos-monitoring

  # default login credentials: admin/admin
  grafana:
    image: grafana/grafana:latest
    env_file: ./grafana/grafana.conf
    container_name: grafana
    volumes:
      - ${PWD}/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ${PWD}/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    networks:
      - cosmos-monitoring

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - cosmos-monitoring