version: "3.5"

networks:
  ava-monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml.edited:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - ava-monitoring

  # default login credentials: admin/admin
  grafana:
    image: grafana/grafana:latest
    env_file: ./grafana/grafana.conf
    container_name: grafana
    volumes:
      - ${PWD}/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ${PWD}/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    networks:
      - ava-monitoring

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--collector.cpu'
      - '--collector.diskstats'
      - '--collector.filesystem'
      - '--collector.loadavg'
      - '--collector.meminfo'
      - '--collector.filefd'
      - '--collector.netdev'
      - '--collector.stat'
      - '--collector.netstat'
      - '--collector.systemd'
      - '--collector.uname'
      - '--collector.vmstat'
      - '--collector.time'
      - '--collector.mdadm'
      - '--collector.zfs'
      - '--collector.tcpstat'
      - '--collector.bonding'
      - '--collector.hwmon'
      - '--collector.arp'    
    ports:
      - 9100:9100
    networks:
      - ava-monitoring