# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerts/celo.rules"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  # celo monitoring
  - job_name: 'celo'
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['NODE_IP:6060']
        labels:
          instance: 'Validator'
      - targets: ['NODE_IP:6060']
        labels:
          instance: 'Proxy'
  # Attestation
  - job_name: 'celo_attest'
    #scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['NODE_IP_OR_DOMAIN']
        labels:
          instance: 'Attestation'
  - job_name: 'node'
    static_configs: 
      - targets: ['NODE_IP:9100']
        labels:
          instance: 'Validator'
      - targets: ['NODE_IP:9100']
        labels:
          instance: 'Proxy'